### ISSUE TITLE
release new crates version with nalgebra 0.27

### ISSUE THREAD

**Issue by whiterabbit42k** [w1th0utnam3/splashsurf#34]
Hello,

Could you release a new version with nalgebra 0.27; I see it's in master, but crates does not appear to work with nalgebra 0.27

Thanks

**Comment by w1th0utnam3** [comment]
I think I'll make a new release soon. For now, you can just point it to the GitHub repository and if you want you can specify a commit hash? For example
```toml
splashsurf_lib = { git = "https://github.com/w1th0utnam3/splashsurf", rev="08cfbea363874cb56dc05e26dde5460fe06205e5" }
```
to get the most recent commit at the moment.

**Comment by whiterabbit42k** [comment]
Yea i generally prefer to not point at git; I can just wait for a new release, if it won't be a long time.

**Comment by w1th0utnam3** [comment]
Today I published a new version, have fun!

**Comment by whiterabbit42k** [comment]
thank you and thanks again for this library !

**Comment by whiterabbit42k** [comment]
sorry it looks like 0.28 got released shortly after, and salva master is now on 0.28; is it possible to bump the crate again? alternatively, could explore api using mint: https://docs.rs/mint/0.5.6/mint/

**Comment by whiterabbit42k** [comment]
ah i see your master is now on 0.28 too; it maybe good to wait until salva gets a crate release so this can be released with whatever nalgebra it has too? but also exploring mint might be a good idea as well :)

**Comment by w1th0utnam3** [comment]
I can look into using mint to make this more explicit. In the meantime you could also use bytmuck (which you would need anyway with mint? At least if you wanted to avoid copies) to convert everything form `splashurf::nalgebra` to your `nalgebra` types. I think it's pretty much guaranteed to work across versions. Because it's also basically guaranteed that `[T; 3]` <-> `Vector3` works.
